### ISSUE TITLE
Pie chart size is incorrect when using Modifier.fillMaxSize(.#f)

### ISSUE THREAD

**Issue by CarlosEsco** [hi-manshu/Charty#32]
When not giving a direct size with `Modifier.size(Some.dp)`, and using `Modifier.fillMaxSize(.#f)` or `Modifier.fillMaxWidth(.#f)` the chart looks fine, however the background size does not wrap the object.  Here are some pictures to compare
 ```
PieChart(
                    modifier = Modifier
                        .scale(1f)
                        .fillMaxWidth(.4f)
                        .background(color = Color.White),
                    pieData = pieData,
                )
```
![image](https://user-images.githubusercontent.com/2092019/187935986-e89a4862-8a28-4ef4-b656-618c54b2027f.png)

```
PieChart(
                    modifier = Modifier
                        .scale(1f)
                        .background(color = Color.White)
                        .size(size.dp),
                    pieData = pieData, config = PieConfig(isDonut = true, expandDonutOnClick = false),
                )
```
![image](https://user-images.githubusercontent.com/2092019/187935930-1fe1c879-6047-43f2-a6dc-8686e76edae6.png)

**Comment by hi-manshu** [comment]
Hey @CarlosEsco ,
Will test it out and fix this if any issue! Thanks for opening the issue. Really appreciate it

**Comment by hi-manshu** [comment]
Hey @CarlosEsco,
fixed it [here](https://github.com/hi-manshu/Charty/releases/tag/v1.1.3-alpha02)

**Comment by CarlosEsco** [comment]
Might want to double check where you host the release as I can't resolve `com.himanshoe:charty:1.1.3-alpha02`

**Comment by hi-manshu** [comment]
Weird. let me check!

**Comment by hi-manshu** [comment]
Hey @CarlosEsco , Please do check now!

**Comment by CarlosEsco** [comment]
Able to pull the jar now, but still having issues with the bottom padding.

![image](https://user-images.githubusercontent.com/2092019/189358135-007ebfe7-d84b-4e36-81c8-b13130c9c4fb.png)

**Comment by CarlosEsco** [comment]
Seems to be an issue with not setting the height.
This also has the same issue
```kotlin
PieChart(
                modifier = Modifier.width(chartSize),
                pieData = pieData, config = PieConfig(isDonut = false, expandDonutOnClick = true),
            )
           ```

**Comment by CarlosEsco** [comment]
looks good thanks!
